all:
	python clock.py config.txt 1 6 &
	python clock.py config.txt 2 6 &
	python clock.py config.txt 3 6 &
	python clock.py config.txt 4 6 &
	python clock.py config.txt 5 6 &
	python clock.py config.txt 6 6 &
